# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('registerTime', models.TimeField(auto_now_add=True, null=True)),
                ('updateTime', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('good_id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('fontPageImg', models.CharField(default='', max_length=200)),
                ('reviews', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('creatTime', models.TimeField(auto_now_add=True, null=True)),
                ('updateTime', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('creatTime', models.TimeField(auto_now_add=True, null=True)),
                ('updateTime', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manage_id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('registerTime', models.TimeField(auto_now_add=True, null=True)),
                ('updateTime', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('userId', models.CharField(default=uuid.uuid4, editable=False, max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('creatTime', models.TimeField(auto_now_add=True, null=True)),
                ('updateTime', models.TimeField(auto_now_add=True, null=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GoodType'),
        ),
    ]
