# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('registerTime', models.TimeField(auto_now_add=True, null=True)),
                ('updateTime', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.IntegerField(auto_created=True)),
                ('goodId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('fontPageImg', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('registerTime', models.TimeField(auto_now_add=True)),
                ('updateTime', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(auto_created=True)),
                ('storeId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GoodType'),
        ),
        migrations.AddField(
            model_name='goods',
            name='storeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Store'),
        ),
    ]
